spring:
  application:
    name: codedocgen-backend
server:
  port: 8080

# Logging configuration
logging:
  level:
    com.codedocgen.service.impl.JavaParserServiceImpl: DEBUG
    # com.codedocgen.service.impl.JavaParserServiceImpl$ClassMetadataVisitor: TRACE # Old name commented out
    com.codedocgen.parser.ClassMetadataVisitorLogger: TRACE # New, simpler logger name
    org.springframework.web: INFO
    org.hibernate.type.descriptor.sql: TRACE # Added for Hibernate SQL logging, if needed later

# Directory for cloned repositories
app:
  repoStoragePath: /tmp/repos # On Windows, this might be C:/tmp/repos or similar. Adjust if needed.
  outputBasePath: ./output # Relative to project root
  docsStoragePath: ${app.outputBasePath}/docs
  diagramsStoragePath: ${app.outputBasePath}/diagrams 