spring:
  application:
    name: codedocgen-backend
server:
  port: 8080

# Logging configuration
logging:
  level:
    com.codedocgen.service.impl.JavaParserServiceImpl: DEBUG
    com.codedocgen.parser.ClassMetadataVisitorLogger: TRACE
    org.springframework.web: INFO
    org.hibernate.type.descriptor.sql: TRACE # Added for Hibernate SQL logging, if needed later

# Directory for cloned repositories
app:
  repoStoragePath: /tmp/repos # On Windows, this might be C:/tmp/repos or similar. Adjust if needed.
  outputBasePath: ./output # Relative to project root
  docsStoragePath: ${app.outputBasePath}/docs
  diagramsStoragePath: ${app.outputBasePath}/diagrams
  
  # Enterprise features
  git:
    username: ${GIT_USERNAME:} # Allow override via env var, empty by default
    password: ${GIT_PASSWORD:} # Allow override via env var, empty by default
    # Added for disk space management when cloning repositories
    shallowClone: true 
    depth: 1 # Clone only 1 commit deep for smaller disk usage
    cloneTimeout: 300 # 5 minutes timeout for clone operations
    
  maven:
    settings:
      path: ${MAVEN_SETTINGS_PATH:} # e.g., /path/to/enterprise/settings.xml or classpath:enterprise-settings.xml
    executable:
      path: ${MAVEN_EXECUTABLE_PATH:mvn} # Defaults to 'mvn' assuming it's on PATH
      
  graphviz:
    dot:
      executable:
        path: ${GRAPHVIZ_DOT_PATH:dot} # Defaults to 'dot' assuming it's on PATH
  
  truststore:
    path: ${TRUSTSTORE_PATH:classpath:truststore.jks} # Path to truststore
    password: ${TRUSTSTORE_PASSWORD:changeit} # Truststore password
  
  # PII/PCI detection settings
  pii-keywords-regex: "(ssn|social\\s*security|credit\\s*card|card\\s*number|cvv|cvc|password|secret|key)"
  pci-keywords-regex: "(card\\s*number|cc\\s*num|cvv|cvc|expir(y|ation)\\s*date)"
  general-sensitive-keywords-regex: "(password|secret|key|token|credential|auth)"
  
  # Resource management settings
  resourceManagement:
    excludeTestDirs: true # Skip processing test directories to save disk space
    maxJarDependencies: 100 # Max number of JARs to process to avoid memory issues
    includeTestScope: false # Don't include test dependencies
    autoCleanup: true # Automatically clean up temporary files
    maxTempFileAge: 1800 # Clean up temporary files older than 30 minutes (in seconds) 